### ISSUE TITLE
linux/i2c-dev.h: No such file or directory

### ISSUE THREAD

**Issue by adel-belasker-stackforce** [Infineon/getstarted-optiga-trust-x#6]
Hi all,
While building getstarted-optiga-trust-x project, without any modifications and using an updated DAVE IDE (version: 4.4.2), I keep receiving this error:
`../Libraries/TrustX/pal/linux/pal_i2c.c:37:27: fatal error: linux/i2c-dev.h: No such file or directory`
Can you give me a hint please, on how can I fix this issue ?
I am using Windows 10 64bit and I followed exactly the instructions mentioned in the wiki page.
Thank you.

kind regards,

**Comment by ayushev** [comment]
Hi,

which build configuration are you using, Release or Debug?

Anyways, you can solve this error by excluding from Build all folders in pal except `xmc_dave`
You can do this by right-click the folder you need to exclude, on the top of drop down menu select to `Resource configuration`, select then `Exclude from Build...`, then select all resulting build configurations and press OK

**Comment by adel-belasker-stackforce** [comment]
Hi,
Thank you for your prompt reply, I am using Debug configuration. Alright.
