### ISSUE TITLE
GetStart-Optiga-Trust-X compilation issue

### ISSUE THREAD

**Issue by ayushev** [Infineon/getstarted-optiga-trust-x#8]
I'm using the Optiga Trust X Eval Kit and downloading the GetStart-Optiga-Trust-X-Master code,
The trust X file under getStarted -Optiga-trust-x-master \Libraries\ trustX is blank. There is a compilation error using the Dave IDE. I need a complete compiled code, can you help me?

_Originally posted by @674544116 in https://github.com/Infineon/getstarted-optiga-trust-x/issues/7#issuecomment-844622179_

**Comment by ayushev** [comment]
Hello @674544116,

how did you get the code, did you follow [this guidance](https://github.com/Infineon/getstarted-optiga-trust-x/wiki#getting-the-code), could it be that you forgot the `--recursive` option?

**Comment by 674544116** [comment]
Hello，@ayushev，I am a ZIP:https://github.com/Infineon/getstarted-optiga-trust-x of the links below to download.

**Comment by ayushev** [comment]
direct zipping doesn't work as this repository has git submodules. I've updaloaded for you a zip package which should have all requried folders inside. Here it is https://github.com/Infineon/getstarted-optiga-trust-x/releases/tag/latest-v1.X

**Comment by ayushev** [comment]
@674544116 can we close the issue?

**Comment by 674544116** [comment]
Yeah， of course.
Thank you very much.



---Original---
From: "Artem ***@***.***&gt;
Date: Wed, May 26, 2021 17:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Infineon/getstarted-optiga-trust-x] GetStart-Optiga-Trust-X compilation issue (#8)




 
@674544116 can we close the issue?
